appName: players-info-frontend 
image:
  repository: benmalekarim/players-info-frontend
  tag: v1.0.0
replicas: 2
service:
  type: NodePort
  nodePort: 30080
rollout:
  enabled: false
  strategy: canary
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
cm:
  config:
    backend_host: http://players-info-backend-service.app.svc.cluster.local:5001/api/players 