{{- if eq .Values.rollout.strategy "blueGreen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service-preview
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ add .Values.service.nodePort 1 }}
{{- end }}
  type: {{ .Values.service.type }}
{{- end }}