apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-template-cm
  labels:
    app: {{ .Values.appName }}
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <title>Flask App</title>
      <style>
        body {
          background-color: {{ '{{ bg_color }}' }};
          color: #333;
          font-family: Arial, sans-serif;
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
          font-size: 2rem;
        }
      </style>
    </head>
    <body>
      {{ '{{ message }}' }}
    </body>
    </html>
