appName: awesome-app
image:
  repository: benmalekarim/awesome-app
  tag: 9622cc03b28f500d545f28ba9fbcf6943aa02ec4
replicas: 4
message: "AWESOME APP"
service:
  type: ClusterIP
  nodePort: ##
rollout:
  enabled: false
