appName: awesome-app
image:
  repository: benmalekarim/awesome-app
  tag: 0676c769cfd5fbcf345a03713eef06cfd0fad1cf
replicas: 2
service:
  type: ClusterIP
  nodePort: ##
rollout:
  enabled: false
  strategy: canary
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
cm:
  config:
    bg_color: "#90EE90"
