{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.appName }}-rollout
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
{{- if eq .Values.rollout.strategy "canary" }}
    canary:
      steps:
        - setWeight: 50
        - pause: {}
{{- else if eq .Values.rollout.strategy "blueGreen" }}
    blueGreen: 
      activeService: {{ .Values.appName }}-service 
      previewService: {{ .Values.appName }}-service-preview
      autoPromotionEnabled: false
{{- end }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
{{- end }}