apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  {{- if .Values.rollout.enabled }}
  replicas: 0
  {{- else }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      annotations:
        checksum/config-cm: {{ include (print $.Template.BasePath "/config-cm.yaml") . | sha256sum }}
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 5001 
          envFrom:
          - configMapRef:
              name: {{ .Values.appName }}-config-cm