name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.0

    - name: Package Helm charts
      run: |
        mkdir -p docs
        for chart in charts/*; do
          helm dependency update "$chart" || true
          helm package "$chart" --destination docs/
        done

    - name: Update Helm repo index
      run: |
        helm repo index docs --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

    - name: Commit and push to GitHub Pages
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/
        git commit -m "Update Helm chart repo index" || echo "No changes to commit"
        git push