name: Package and Publish Helm Chart to docs/

on:
  push:
    branches:
      - main
    #paths:
    #  - 'charts/**'

jobs:
  package-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: |
          helm package charts --destination docs/

      - name: Update index.yaml
        run: |
          helm repo index docs --url https://BENMALEKarim.github.io/awesome-app-helm

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update Helm chart index"
          git push